version: "3.9"
x-default-logging:
  # driver: "json-file"
  # options:
  #   max-size: "5m"
  #   max-file: "2"
  &logging
  driver: loki
  options:
    loki-url: http://127.0.0.1:3100/loki/api/v1/push

services:
  ########
  # Mimir
  #######
  minio:
    image: minio/minio
    entrypoint: [ "" ]
    # 必要なバケット分ディレクトリ作る
    command:
      [
        "sh",
        "-c",
        "mkdir -p /data/mimir && mkdir -p /data/tempo && mkdir -p /data/otelcol && minio server --quiet /data --address :9000 --console-address :9001"
      ]
    environment:
      - MINIO_ROOT_USER=mimir
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data
    ports:
      - 9001:9001
    logging: *logging
    depends_on:
      - loki

  mimir:
    image: grafana/mimir:latest
    command:
      - "-config.file=/etc/mimir.yaml"
    hostname: mimir
    depends_on:
      - minio
      - loki
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-data:/data
    ports:
      - 9009:9009
    logging: *logging

  #######################
  # Prometheus
  #######################

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.enable-remote-write-receiver # tempoからのremote-write受信のため
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - "--enable-feature=exemplar-storage" # examplar の保存
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"
    logging: *logging
    depends_on:
      - mimir
      - loki

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    logging: *logging
    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    logging: *logging
    depends_on:
      - loki

  process-exporter:
    image: ncabatoff/process-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - ./config/process-exporter.yml:/config/config.yml
    command:
      - "--procfs=/host/proc"
      - "-config.path=/config/config.yml"
    ports:
      - 9256
    depends_on:
      - loki

  ########################
  # Loki
  ########################
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/data/loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log:ro
      - ./config/promtail-local-config.yaml:/etc/promtail/config.yaml:ro
    command: -config.file=/etc/promtail/config.yml
    logging: *logging
    depends_on:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning/:/etc/grafana/provisioning/
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    logging: *logging
    depends_on:
      - loki

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
    logging: *logging
    depends_on:
      - loki

  ###################
  # Tempo
  ##################
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "14268" # jaeger ingest
      - "3200" # tempo
      - "4317" # otlp grpc
      - "4318" # otlp http
      - "9411" # zipkin
    logging: *logging
    depends_on:
      - minio
      - loki

  ####################
  # OTEL
  ##################

  # And put them in an OTEL collector pipeline...
  otel-collector:
    # image: otel/opentelemetry-collector:0.61.0
    # image: otel/opentelemetry-collector-contrib:0.91.0
    build: ./otelcol-build
    environment:
      - AWS_ACCESS_KEY_ID=mimir
      - AWS_SECRET_ACCESS_KEY=supersecret
    command:
      - "--config=/etc/otelcol-config.yml"
    volumes:
      - ./config/otelcol-config.yml:/etc/otelcol-config.yml
      - ./data/otelcol:/data
    ports:
      - "4317" # OTLP over gRPC receiver
      - "4318:4318" # OTLP over HTTP receiver
      - "9464" # Prometheus exporter
      - "8888" # metrics endpoint
    depends_on:
      - loki
      - minio

  ######
  ## App
  #######
  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
    ports:
      - 3002:3000

  java-demo-app:
    build: ./java-demo-app
    ports:
      - 8081:8081
    logging: *logging
    depends_on:
      - loki

  golang-demo-app:
    build: ./golang-demo-app
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=prod,service.version=0.0.1
      - OTEL_SERVICE_NAME=golang-demo-app
      - VERSION=0.0.1
      - ENV=prod
      - PING_TARGET_URL=http://java-demo-app:8081
    ports:
      - 3001:3000
    logging: *logging
    depends_on:
      - loki

  golang-kafka-producer:
    build: ./golang-kafka-producer
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=prod,service.version=0.0.1
      - OTEL_SERVICE_NAME=golang-kafka-producer
      - VERSION=0.0.1
      - ENV=prod
    ports:
      - 3003:3000
    logging: *logging
    depends_on:
      - kafka
      - loki

  golang-kafka-consumer:
    build: ./golang-kafka-consumer
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=prod,service.version=0.0.1
      - OTEL_SERVICE_NAME=golang-kafka-consumer
      - VERSION=0.0.1
      - ENV=prod
    logging: *logging
    depends_on:
      - kafka
      - loki

  kafka:
    image: confluentinc/cp-kafka:7.5.2
    container_name: kafka
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_HEAP_OPTS=-Xmx200m -Xms200m
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@0.0.0.0:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_NODE_ID=1
      - KAFKA_METADATA_LOG_SEGMENT_MS=15000
      - KAFKA_METADATA_MAX_RETENTION_MS=60000
      - KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS=2800
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - CLUSTER_ID=ckjPoprWQzOf0-FuNkGfFQ

    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    logging: *logging
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8082:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command: [ "--kafka.server=kafka:9092" ]
    ports:
      - 9308:9308

  envoyproxy:
    build: ./frontendproxy
    environment:
      - OTEL_COLLECTOR_HOST=otel-collector
      - OTEL_COLLECTOR_PORT_GRPC=4317
      - OTEL_COLLECTOR_PORT_HTTP=4318
    ports:
      - 8080:8080
    logging: *logging
    depends_on:
      - loki

volumes:
  minio-data:
  mimir-data:
  grafana-data:
  loki-data:
  tempo-data:
  kafka-data:
