{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   { "name": "receiver", "label": "receiver", "query": { "query": "label_values()" } },
   {
    "name": "processes",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   },
   { "name": "exporter", "label": "exporter", "query": { "query": "label_values()" } }
  ]
 },
 "panels": [
  {
   "title": "Node CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "timeseries",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{receriver}} accepted"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{receiver=~\"$receiver\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} refused"
    }
   ]
  },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "timeseries",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 4, "w": 12, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent / sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed /sec"
    }
   ]
  },
  {
   "title": "process cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(namedprocess_namegroup_cpu_seconds_total{groupname=~\"$processes\"}[1m])) by (groupname) ",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Span Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, service_name) (rate(duration_milliseconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "nodeGraph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 17 },
   "targets": [
    { "limit": 20, "tableType": "traces" }
   ]
  }
 ]
}