# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:
  file/traces:
    path: /tmp/otel-logs/traces.log
    format: json
  file/metrics:
    path: /tmp/otel-logs/metrics.log
    format: json
  file/logs:
    path: /tmp/otel-logs/logs.log
    format: json
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "otel-collector:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

connectors:
  spanmetrics:

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, spanmetrics, file/traces, otlp/tempo]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter, batch]
      exporters: [logging, file/metrics, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, file/logs]