# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:
  file/traces:
    path: /tmp/otel-logs/traces.log
    format: json
  file/metrics:
    path: /tmp/otel-logs/metrics.log
    format: json
  file/logs:
    path: /tmp/otel-logs/logs.log
    format: json

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, spanmetrics]
#      exporters: [logging, spanmetrics, file/traces]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter, batch]
      exporters: [logging]
#      exporters: [logging, file/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
#      exporters: [logging, file/logs]
