# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:
    verbosity: detailed
  awss3:
    s3uploader:
      s3_bucket: otelcol
      endpoint: minio:9000
      s3_force_path_style: true
      disable_ssl: true
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    # endpoint: http://mimir:9009/api/v1/push
    tls:
      insecure: true
    send_metadata: true
    resource_to_telemetry_conversion:
      enabled: true

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

connectors:
  spanmetrics:
    exemplars:
      enabled: true
      max_per_data_point: 10000

service:
  telemetry:
    logs:
      level: INFO
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics, otlp/tempo, awss3]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter, batch]
      exporters: [prometheusremotewrite, awss3]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, awss3]
