# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

exporters:
#  otlp:
#    endpoint: "jaeger:4317"
#    tls:
#      insecure: true
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "otel-collector:9464"
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

service:
  pipelines:
    traces:
      exporters: [logging, spanmetrics, otlp/tempo]
#      exporters: [otlp, logging, spanmetrics, otlp/tempo]
    metrics:
      exporters: [prometheus, logging]
