process_names:
  - name: "{{.ExeBase}};{{.Username}};{{.Matches.cmdline}}"
    comm:
      - java
      - app
      - otelcol-contrib
      - otelcol-custom
      - prometheus
      - tempo
    cmdline: 
    - (?P<cmdline>.*)