---
global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    cluster: demo
    namespace: demo

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "loki"
    dns_sd_configs:
      - names:
          - loki
        type: A
        port: 3100

  - job_name: "promtail"
    dns_sd_configs:
      - names:
          - promtail
        type: A
        port: 9080

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: otel
    honor_labels: true
    static_configs:
      - targets:
          - "otel-collector:9464"
  - job_name: otel-collector
    static_configs:
      - targets:
          - "otel-collector:8888"

# remote_write:
#   - url: http://victoriametrics:8428/api/v1/write

